version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6
  node: circleci/node@5.0.0

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm test
      - coveralls/upload:
          verbose: true

workflows:
  test_and_coverage:
    jobs:
      - test
